**Name of students:**

Nave lutzky ID :206263154

Shirel Harel ID: 209130012

In [1]:
import numpy as np
import pandas as pd

**Solution to question 1:**  

open the file to read  and return the first five lines

In [2]:
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
vacc_df = pd.read_csv(url)

In [3]:
vacc_df.head()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0

**Solution to question 2:**

we chose Norway because it begins with "N" like Nave

In [4]:
vacc_df[vacc_df['location'].str.contains('No')]

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
5708,North America,OWID_NAM,2020-12-14,5.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
5709,North America,OWID_NAM,2020-12-15,723.0,0.0,NaN,718.0,718.0,0.00,0.00,NaN,1.0
5710,North America,OWID_NAM,2020-12-16,3023.0,0.0,NaN,2300.0,1509.0,0.00,0.00,NaN,3.0
5711,North America,OWID_NAM,2020-12-17,7202.0,0.0,NaN,4179.0,2399.0,0.00,0.00,NaN,4.0
5712,North America,OWID_NAM,2020-12-18,11174.0,0.0,NaN,3972.0,2792.0,0.00,0.00,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6033,Norway,NOR,2021-03-20,769667.0,506599.0,263068.0,473.0,8786.0,14.20,9.34,4.85,1621.0
6034,Norway,NOR,2021-03-21,769922.0,506786.0,263136.0,255.0,8806.0,14.20,9.35,4.85,1624.0
6035,Norway,NOR,2021-03-22,771494.0,508288.0,263206.0,1572.0,8955.0,14.23,9.38,4.86,1652.0
6036,Norway,NOR,2021-03-23,785242.0,521133.0,264109.0,13748.0,10024.0,14.48,9.61,4.87,1849.0
6037,Norway,NOR,2021-03-24,824447.0,557043.0,267404.0,39205.0,12122.0,15.21,10.28,4.93,2236.0

**Solution to question 3:**

there are X rows in our file, we computed the answer in the following way:

 הערה: מספר הרשומות הוא כמספר המפעמים שנספרת המילה לוקיישן כי לא יכול להיות מצב שיהיה שם ערך חסר

In [5]:
our_country = vacc_df.loc[vacc_df.location=='Norway']
our_country.count()["location"]

88

**Solution to question 4:**

We found the max vaccinations for day then we found the date there were the max vaccinations for day

In [6]:
vacc_Norway_df = vacc_df.loc[vacc_df.location == 'Norway']
max_vacc = vacc_Norway_df.daily_vaccinations.max()
line_date = vacc_Norway_df.loc[vacc_Norway_df.daily_vaccinations == max_vacc]
pd.DataFrame(line_date.date)

            date
6023  2021-03-10

**Solution to question 5:**

We show the first 3 lines of the country we choose, and the columns: 'location', 'date','daily_vaccinations'

In [7]:
vacc_Norway_df.head(3).loc[::,['location','date','daily_vaccinations']]

     location        date  daily_vaccinations
5950   Norway  2020-12-27                 NaN
5951   Norway  2020-12-28               603.0
5952   Norway  2020-12-29               835.0

**Solution to question 6:**

We calculate the daily_vaccinations mean by using the function "mean( )"

In [8]:
#מספר המתחסנים הממוצע מידי יום במדינה שבחרנו
vacc_Norway_df['daily_vaccinations'].mean()

8973.87356321839

**Solution to question 7:**

We show the both columns: "date" and "people_vaccinated_per_hundred" (without NaN at the column "people_vaccinated_per_hundred")

In [9]:
#הצגנו רק את הימים עם נתונים עבור העמודה המבוקשת ללא ערכים חסרים
without_nan =vacc_Norway_df.dropna(subset = ['people_vaccinated_per_hundred'])
without_nan.loc[::,['date','people_vaccinated_per_hundred']]

            date  people_vaccinated_per_hundred
5950  2020-12-27                           0.00
5951  2020-12-28                           0.01
5952  2020-12-29                           0.03
5953  2020-12-30                           0.04
5954  2020-12-31                           0.04
...          ...                            ...
6033  2021-03-20                           9.34
6034  2021-03-21                           9.35
6035  2021-03-22                           9.38
6036  2021-03-23                           9.61
6037  2021-03-24                          10.28

[88 rows x 2 columns]

**Solution to question 8:**

We calculate harmonic mean to the column 'people_vaccinated_per_hundred' (after losing the places where there were 0)

In [10]:

without_zero_and_nan = without_nan[without_nan.loc[:,'people_vaccinated_per_hundred']!=0]
from scipy import stats
stats.hmean(without_zero_and_nan.loc[:,'people_vaccinated_per_hundred'])

0.25878183122570564

**Solution to question 9:**
In order to know what is bigger- the mean or the median for the column "daily_vaccinations", we calculate the mean and the median and compered

In [11]:
median_Norway = vacc_Norway_df['daily_vaccinations'].median()
mean_Norway = vacc_Norway_df['daily_vaccinations'].mean()
if median_Norway > mean_Norway:
    print ('median is bigger than mean')
else:
    print ('mean is bigger than median')

median is bigger than mean